### ISSUE TITLE
Eval log file limiting examples

### ISSUE THREAD

**Issue by molereddy** [locuslab/tofu#17]
Why do the evals happen on smaller files? 

These lines handle it 

`eval_result_dict[k][metric] = interleave(a, b, bsz)[:total_len]`
https://github.com/locuslab/tofu/blob/8889542f281f7fca9ad23dbc11a4cb253ee2aa65/utils.py#L81C71-L81C76 

`def get_total_len(name, forget_rate):` https://github.com/locuslab/tofu/blob/8889542f281f7fca9ad23dbc11a4cb253ee2aa65/utils.py#L42

returns only 300 for forget10, though forget10 has 400 examples. Is there a reason for this?

**Comment by zhilif** [comment]
It should be deprecated I guess. The interleaving code shouldn't be used anymore.
