### ISSUE TITLE
Command for evaluations

### ISSUE THREAD

**Issue by yujianll** [locuslab/tofu#2]
Hi! I wonder if you could provide the command for evaluating an unlearned model?

**Comment by zhilif** [comment]
We are currently doing some refactor to better cope with multigpu evaluation, we will update the code as soon as that refactor is done, thanks for your interest!

**Comment by zhilif** [comment]
@yujianll Hi, can you take a look at the updated evaluation pipeline and let us know if that's helpful, thanks!
