### ISSUE TITLE
TOFU-finetuned Phi-1.5 is not on the huggingface page

### ISSUE THREAD

**Issue by molereddy** [locuslab/tofu#23]
https://huggingface.co/locuslab/tofu_ft_phi-1.5/tree/main
I don't see the model checkpoints here, unlike with llama https://huggingface.co/locuslab/tofu_ft_llama2-7b/tree/main
Also, it would be helpful if the code directly loaded (or had an option to load) the finetuned checkpoints from here for the leaderboard, instead of running `finetune.py`

**Comment by pratyushmaini** [comment]
Thanks for pointing this out and for the great suggestion. Uploaded to huggingface, and updated the model config to use the huggingface path as default. Let me know if this looks good, and feel free to close the issue.
