### ISSUE TITLE
Inconsistent number of forget samples when evaluating  the retain model (forget10 task)

### ISSUE THREAD

**Issue by LetheSec** [locuslab/tofu#32]
Hi, thanks for the great work! 

For the **forge10** task, the forget set should be **400** samples , as shown in `forget10.json` . However,  there are only **300** samples are used for the evaluation, as shown in `eval_log_forget.json`.
https://github.com/locuslab/tofu/blob/36811054f2376560c8d6629667059f3000e5603c/data/ft_epoch5_lr1e-05_llama2-7b_retain90_wd0.01/eval_results/ds_size300/eval_log_forget.json#L2404

Can you explain why you do this?  Thank you so much.

**Comment by zhilif** [comment]
In the config file https://github.com/locuslab/tofu/blob/main/config/eval_everything.yaml#L30, we specify the maximum number of samples for evaluation to be 300, for evaluation speed.

**Comment by LetheSec** [comment]
Thank you for your reply.
