### ISSUE TITLE
Inquiry about Constructing Datasets with Elaborate Prompt

### ISSUE THREAD

**Issue by tbozhong** [locuslab/tofu#33]
Hi there,

Thanks for your contributions to the community!

I am currently following your work, but I have encountered some issues while trying to construct datasets. The paper mentions, 
> To this end, we use an elaborate prompt that deterministically seeds various author attributes such as their place/time of birth, gender orientation, genre, the occupation of their parents, words in the title of their books, and soon. 

However, I was unable to find the `elaborate prompt` mentioned.

Could you please assist me in how to utilize this prompt to construct my own dataset?

I look forward to your response, and once again, thank you for your contributions!

Best regards.

**Comment by zhilif** [comment]
Can you check out https://github.com/locuslab/tofu/blob/refactor_eval/notebook/data_generation/gpt_gen_authors.ipynb?
