### ISSUE TITLE
Could you please provide finetuned model weight of phi-1.5 and lamma2, this will unify the basis of our research.

### ISSUE THREAD

**Issue by Yuda-Jin** [locuslab/tofu#39]
Could you please provide finetuned model weight of phi-1.5 and lamma2, this will unify the basis of our research. As a new reseacher in this field, it is vary useful,

**Comment by pratyushmaini** [comment]
The model links on huggingface can be found below:

`https://huggingface.co/locuslab/tofu_ft_phi-1.5`

`https://huggingface.co/locuslab/tofu_ft_llama2-7b`
