### ISSUE TITLE
Raise error while evaluate.

### ISSUE THREAD

**Issue by Yuda-Jin** [locuslab/tofu#40]
when I was evaluating a fintuned phi-1.5 model using following command
`CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node=1  evaluate_util.py model_family=$model_family split=$split model_path=$model_path`
An error raised. It could not find 'paraphrased_answer' key in dataset. How to fix it?
![image](https://github.com/user-attachments/assets/86acf72c-b480-4d05-b2b8-f3e0e7eed71a)

**Comment by Yuda-Jin** [comment]
more specifically, how to eval the forget quality? I have changed the eval_everything.yaml like this, and eval the full finetuned phi model on retain99 dataset, but get model quality is 1. I think it should be closed to 0 rather than 1, because baseline has different distribution from retrain model accroding to your paper. What is wrong?
![image](https://github.com/user-attachments/assets/2d088f13-8ff1-47d7-9e6d-4c752ca9178e)

**Comment by Yuda-Jin** [comment]
I have finished.

**Comment by kyj93790** [comment]
Hello,

I am encountering the same issue and would greatly appreciate your guidance on how to resolve this problem. Could you please share any insights or solutions you might have?

**Comment by Yuda-Jin** [comment]
use perturbed dataset to eval

**Comment by kyj93790** [comment]
> use perturbed dataset to eval

Thank you for letting me know! I'm glad I could help you solve the problem.
Wishing you all the best and lots of good things ahead
