### ISSUE TITLE
Can not find 'adapter_config.json' in ckpt or huggingface

### ISSUE THREAD

**Issue by Yuda-Jin** [locuslab/tofu#41]
![image](https://github.com/user-attachments/assets/63e88485-59b0-40f6-b6d5-da6dc9edd945)
error raised when I was running forget.py

**Comment by AdvitDeepak** [comment]
Hi! I ran into the same issue and wanted to ask how you resolved it?

**Comment by Yuda-Jin** [comment]
That is, you should load tokenizer using offical llama2 path, and load pretrained weight using tofu model path.
