### ISSUE TITLE
Is the dpo loss wrong?

### ISSUE THREAD

**Issue by HaomingX** [locuslab/tofu#44]
Why is loss assigned three consecutive values?
<img width="637" alt="c7a48db47f4f5f530254d5ca93ba9ad" src="https://github.com/user-attachments/assets/840b1848-e70f-43b9-a262-c35c85192547">

**Comment by zhilif** [comment]
Sorry I know it's confusing, this part of the code is not maintained and we didn't use them anywhere... will clean that up later

**Comment by pratyushmaini** [comment]
As Zhili mentioned, we did not use this loss as it was not converging well for us and the general idk and KL losses worked better. I have fixed the thing we used for debugging in the latest commit https://github.com/locuslab/tofu/commit/80159d8ea39edf147fb09cd82aefa08e506e6718
Thanks for pointing it to us!

**Comment by HaomingX** [comment]
> As Zhili mentioned, we did not use this loss as it was not converging well for us and the general idk and KL losses worked better. I have fixed the thing we used for debugging in the latest commit [80159d8](https://github.com/locuslab/tofu/commit/80159d8ea39edf147fb09cd82aefa08e506e6718) Thanks for pointing it to us!

Thank you for answering. 
I want to ask another question: why this dpo fail to train models to answering "I don't know"?
I'd appreciate it if you could help me with that.
