### ISSUE TITLE
Finetune LLAMA2 with LoRA

### ISSUE THREAD

**Issue by petezone** [locuslab/tofu#5]
Hi,

Thank you for providing the unlearning dataset and benchmark. I am wondering if finetune LLAMA2 with LoRa is applicable with your code? I found the config file seems does not agree with the finetune code and when I run the code it threws the error: 
Key 'gradient_accumulation_steps' is not in struct
    full_key: gradient_accumulation_steps
    object_type=dict
Could you please kindly help check if there is anything that I might be wrong. Thanks!

**Comment by pratyushmaini** [comment]
Hi, this code based is not intended for working with LoRA. We did initially do experiments with that which is why some functionality still supports it. We observe much better results without LoRA and did not make that available in the release.
