### ISSUE TITLE
requirements.txt needs a fix

### ISSUE THREAD

**Issue by molereddy** [locuslab/tofu#6]
using `pip install -r requirements.txt` gives an error.

ERROR: Invalid requirement: flash-attn --no-build-isolation
pip: error: no such option: --no-build-isolation

It looks like flash-attn must be installed via a command separately `pip install flash-attention --no-build-isolation`

**Comment by pratyushmaini** [comment]
Hi, I reran the whole installation process at my end seeing this comment, and i do not encounter any error. Can you share more details about the system you are using, the pip version, and if you followed all the steps?

**Comment by pratyushmaini** [comment]
I have been able to reproduce the error on an older machine. Thanks for pointing this out!

Updated the readme and requirements accordingly.
