### ISSUE TITLE
Unable to save finetuned llama2

### ISSUE THREAD

**Issue by shaswati1** [locuslab/tofu#7]
Hi,

Thanks for the awesome work. I have been trying to finetune llama2_7b and could successfully train it on this dataset with batch size 1 for 5 epochs. However, while saving the checkpoint at the end of finetuning I am getting the below error:

`torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 153483) of binary: /.../.../.conda/envs/tofu/bin/python`

Can anyone help me regarding this?

**Comment by pratyushmaini** [comment]
Hi, is this error only with llama? or with phi as well.

**Comment by shaswati1** [comment]
> Hi, is this error only with llama? or with phi as well.

I have encountered it for llama only, didn't see it for phi.

**Comment by pratyushmaini** [comment]
1. Can you share the full error stack
2. Does the system have enough space for saving?

**Comment by shaswati1** [comment]
1. I have sent you an email with the same subject as this issue where I attached the full error trace.
2. How much storage does it require? I have ~130G available space on my machine.

**Comment by pratyushmaini** [comment]
Thank you for sharing the error log. This arises from 
https://discuss.huggingface.co/t/help-with-llama-2-finetuning-setup/50035

Pushed a fix to the code. Thanks for trying out TOFU!

**Comment by shaswati1** [comment]
Thanks for the quick fix, really appreciate it! I'm trying that out rn.

**Comment by pratyushmaini** [comment]
Please feel free to close this issue if it works for you now.

**Comment by shaswati1** [comment]
Thanks a lot, the fix worked for both LoRA and w/o LoRA.
